/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// Who performed the action
    /// </summary>
    [DataContract(Name = "Action_source")]
    public partial class ActionSource : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionSource" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActionSource() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionSource" /> class.
        /// </summary>
        /// <param name="uniqueId">A player unique id (UUID) (required).</param>
        /// <param name="name">name (required).</param>
        public ActionSource(Guid uniqueId = default(Guid), string name = default(string))
        {
            this.UniqueId = uniqueId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ActionSource and cannot be null");
            }
            this.Name = name;
        }

        /// <summary>
        /// A player unique id (UUID)
        /// </summary>
        /// <value>A player unique id (UUID)</value>
        /*
        <example>c1d60c50-70b5-4722-8057-87767557e50d</example>
        */
        [DataMember(Name = "uniqueId", IsRequired = true, EmitDefaultValue = true)]
        public Guid UniqueId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /*
        <example>Luck</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionSource {\n");
            sb.Append("  UniqueId: ").Append(UniqueId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.UniqueId != null) {
                // UniqueId (Guid) pattern
                Regex regexUniqueId = new Regex(@"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", RegexOptions.CultureInvariant);
                if (!regexUniqueId.Match(this.UniqueId.ToString()).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UniqueId, must match a pattern of " + regexUniqueId, new [] { "UniqueId" });
                }
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
