/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// GetActions200Response
    /// </summary>
    [DataContract(Name = "get_actions_200_response")]
    public partial class GetActions200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetActions200Response" /> class.
        /// </summary>
        /// <param name="entries">entries.</param>
        /// <param name="overallSize">overallSize.</param>
        public GetActions200Response(List<Action> entries = default(List<Action>), int overallSize = default(int))
        {
            this.Entries = entries;
            this.OverallSize = overallSize;
        }

        /// <summary>
        /// Gets or Sets Entries
        /// </summary>
        [DataMember(Name = "entries", EmitDefaultValue = false)]
        public List<Action> Entries { get; set; }

        /// <summary>
        /// Gets or Sets OverallSize
        /// </summary>
        [DataMember(Name = "overallSize", EmitDefaultValue = false)]
        public int OverallSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetActions200Response {\n");
            sb.Append("  Entries: ").Append(Entries).Append("\n");
            sb.Append("  OverallSize: ").Append(OverallSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
