/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// Represents where a log entry is from
    /// </summary>
    /// <value>Represents where a log entry is from</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LogBroadcastEventOrigin
    {
        /// <summary>
        /// Enum Local for value: local
        /// </summary>
        [EnumMember(Value = "local")]
        Local = 1,

        /// <summary>
        /// Enum LocalApi for value: local_api
        /// </summary>
        [EnumMember(Value = "local_api")]
        LocalApi = 2,

        /// <summary>
        /// Enum Remote for value: remote
        /// </summary>
        [EnumMember(Value = "remote")]
        Remote = 3
    }

}
