/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// Called when a log entry is about to be sent to notifiable players on the platform
    /// </summary>
    [DataContract(Name = "LogBroadcastEvent")]
    public partial class LogBroadcastEvent : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Origin
        /// </summary>
        [DataMember(Name = "origin", IsRequired = true, EmitDefaultValue = true)]
        public LogBroadcastEventOrigin Origin { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LogBroadcastEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LogBroadcastEvent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LogBroadcastEvent" /> class.
        /// </summary>
        /// <param name="entry">entry (required).</param>
        /// <param name="origin">origin (required).</param>
        public LogBroadcastEvent(Action entry = default(Action), LogBroadcastEventOrigin origin = default(LogBroadcastEventOrigin))
        {
            // to ensure "entry" is required (not null)
            if (entry == null)
            {
                throw new ArgumentNullException("entry is a required property for LogBroadcastEvent and cannot be null");
            }
            this.Entry = entry;
            this.Origin = origin;
        }

        /// <summary>
        /// Gets or Sets Entry
        /// </summary>
        [DataMember(Name = "entry", IsRequired = true, EmitDefaultValue = true)]
        public Action Entry { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogBroadcastEvent {\n");
            sb.Append("  Entry: ").Append(Entry).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
