/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// The request parameters for a permission check.
    /// </summary>
    [DataContract(Name = "PermissionCheckRequest")]
    public partial class PermissionCheckRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionCheckRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PermissionCheckRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PermissionCheckRequest" /> class.
        /// </summary>
        /// <param name="permission">The permission to check for (required).</param>
        /// <param name="queryOptions">queryOptions.</param>
        public PermissionCheckRequest(string permission = default(string), QueryOptions queryOptions = default(QueryOptions))
        {
            // to ensure "permission" is required (not null)
            if (permission == null)
            {
                throw new ArgumentNullException("permission is a required property for PermissionCheckRequest and cannot be null");
            }
            this.Permission = permission;
            this.QueryOptions = queryOptions;
        }

        /// <summary>
        /// The permission to check for
        /// </summary>
        /// <value>The permission to check for</value>
        /*
        <example>minecraft.command.ban</example>
        */
        [DataMember(Name = "permission", IsRequired = true, EmitDefaultValue = true)]
        public string Permission { get; set; }

        /// <summary>
        /// Gets or Sets QueryOptions
        /// </summary>
        [DataMember(Name = "queryOptions", EmitDefaultValue = false)]
        public QueryOptions QueryOptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PermissionCheckRequest {\n");
            sb.Append("  Permission: ").Append(Permission).Append("\n");
            sb.Append("  QueryOptions: ").Append(QueryOptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Permission (string) minLength
            if (this.Permission != null && this.Permission.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Permission, length must be greater than 1.", new [] { "Permission" });
            }

            yield break;
        }
    }

}
