/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// The statuses returned in a PlayerSaveResult
    /// </summary>
    /// <value>The statuses returned in a PlayerSaveResult</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PlayerSaveResultOutcome
    {
        /// <summary>
        /// Enum CleanInsert for value: clean_insert
        /// </summary>
        [EnumMember(Value = "clean_insert")]
        CleanInsert = 1,

        /// <summary>
        /// Enum NoChange for value: no_change
        /// </summary>
        [EnumMember(Value = "no_change")]
        NoChange = 2,

        /// <summary>
        /// Enum UsernameUpdated for value: username_updated
        /// </summary>
        [EnumMember(Value = "username_updated")]
        UsernameUpdated = 3,

        /// <summary>
        /// Enum OtherUniqueIdsPresentForUsername for value: other_unique_ids_present_for_username
        /// </summary>
        [EnumMember(Value = "other_unique_ids_present_for_username")]
        OtherUniqueIdsPresentForUsername = 4
    }

}
