/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// Represents the type of synchronisation task
    /// </summary>
    /// <value>Represents the type of synchronisation task</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SyncType
    {
        /// <summary>
        /// Enum Full for value: full
        /// </summary>
        [EnumMember(Value = "full")]
        Full = 1,

        /// <summary>
        /// Enum SpecificUser for value: specific_user
        /// </summary>
        [EnumMember(Value = "specific_user")]
        SpecificUser = 2
    }

}
