/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// Controls how the implementation should behave when new temporary nodes are set that would otherwise conflict with existing entries.
    /// </summary>
    /// <value>Controls how the implementation should behave when new temporary nodes are set that would otherwise conflict with existing entries.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TemporaryNodeMergeStrategy
    {
        /// <summary>
        /// Enum AddNewDurationToExisting for value: add_new_duration_to_existing
        /// </summary>
        [EnumMember(Value = "add_new_duration_to_existing")]
        AddNewDurationToExisting = 1,

        /// <summary>
        /// Enum ReplaceExistingIfDurationLonger for value: replace_existing_if_duration_longer
        /// </summary>
        [EnumMember(Value = "replace_existing_if_duration_longer")]
        ReplaceExistingIfDurationLonger = 2,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None = 3
    }

}
