/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// A request to promote or demote a user along a track.
    /// </summary>
    [DataContract(Name = "TrackRequest")]
    public partial class TrackRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TrackRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackRequest" /> class.
        /// </summary>
        /// <param name="track">track (required).</param>
        /// <param name="context">A set of context pairs..</param>
        public TrackRequest(string track = default(string), List<Context> context = default(List<Context>))
        {
            // to ensure "track" is required (not null)
            if (track == null)
            {
                throw new ArgumentNullException("track is a required property for TrackRequest and cannot be null");
            }
            this.Track = track;
            this.Context = context;
        }

        /// <summary>
        /// Gets or Sets Track
        /// </summary>
        /*
        <example>staff</example>
        */
        [DataMember(Name = "track", IsRequired = true, EmitDefaultValue = true)]
        public string Track { get; set; }

        /// <summary>
        /// A set of context pairs.
        /// </summary>
        /// <value>A set of context pairs.</value>
        [DataMember(Name = "context", EmitDefaultValue = false)]
        public List<Context> Context { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackRequest {\n");
            sb.Append("  Track: ").Append(Track).Append("\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Track (string) minLength
            if (this.Track != null && this.Track.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Track, length must be greater than 1.", new [] { "Track" });
            }

            yield break;
        }
    }

}
