/*
 * LuckPerms REST API
 *
 * The LuckPerms REST API allows developers to query LuckPerms data using HTTP calls.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HighgeekNet.OpenApi.LuckPermsApi.Client.OpenAPIDateConverter;

namespace HighgeekNet.OpenApi.LuckPermsApi.Model
{
    /// <summary>
    /// User
    /// </summary>
    [DataContract(Name = "User")]
    public partial class User : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected User() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="User" /> class.
        /// </summary>
        /// <param name="uniqueId">A player unique id (UUID) (required).</param>
        /// <param name="username">username.</param>
        /// <param name="parentGroups">parentGroups.</param>
        /// <param name="nodes">A map (array) of nodes. (required).</param>
        /// <param name="metadata">metadata (required).</param>
        public User(Guid uniqueId = default(Guid), string username = default(string), List<string> parentGroups = default(List<string>), List<Node> nodes = default(List<Node>), Metadata metadata = default(Metadata))
        {
            this.UniqueId = uniqueId;
            // to ensure "nodes" is required (not null)
            if (nodes == null)
            {
                throw new ArgumentNullException("nodes is a required property for User and cannot be null");
            }
            this.Nodes = nodes;
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for User and cannot be null");
            }
            this.Metadata = metadata;
            this.Username = username;
            this.ParentGroups = parentGroups;
        }

        /// <summary>
        /// A player unique id (UUID)
        /// </summary>
        /// <value>A player unique id (UUID)</value>
        /*
        <example>c1d60c50-70b5-4722-8057-87767557e50d</example>
        */
        [DataMember(Name = "uniqueId", IsRequired = true, EmitDefaultValue = true)]
        public Guid UniqueId { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        /*
        <example>Luck</example>
        */
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets ParentGroups
        /// </summary>
        [DataMember(Name = "parentGroups", EmitDefaultValue = false)]
        public List<string> ParentGroups { get; set; }

        /// <summary>
        /// A map (array) of nodes.
        /// </summary>
        /// <value>A map (array) of nodes.</value>
        [DataMember(Name = "nodes", IsRequired = true, EmitDefaultValue = true)]
        public List<Node> Nodes { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public Metadata Metadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class User {\n");
            sb.Append("  UniqueId: ").Append(UniqueId).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  ParentGroups: ").Append(ParentGroups).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.UniqueId != null) {
                // UniqueId (Guid) pattern
                Regex regexUniqueId = new Regex(@"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", RegexOptions.CultureInvariant);
                if (!regexUniqueId.Match(this.UniqueId.ToString()).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for UniqueId, must match a pattern of " + regexUniqueId, new [] { "UniqueId" });
                }
            }

            // Username (string) minLength
            if (this.Username != null && this.Username.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Username, length must be greater than 1.", new [] { "Username" });
            }

            yield break;
        }
    }

}
